# fly.toml file generated for spkulehas-api on 2022-09-12T16:29:00-06:00

app = "spkulehas-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "../Dockerfile"
  ignorefile = "../.dockerignore"

[env]
  BASE_URL = "https://fly.io/apps/spkulehas-api/api/v1/"
  NODE_ENV = "production"
  PORT = "8080"
  HOSTNAME="0.0.0.0"
  TZ = "America/Denver"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "15s"
    grace_period = "10s"
    method = "get"
    path = "/api/v1/monitor"
    protocol = "http"
    timeout = "2s"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[deploy]
  release_command = "node ./node_modules/knex/bin/cli.js migrate:latest && node ./node_modules/knex/bin/cli.js seed:run --specific=add_2027_reservations.cjs && node ./node_modules/knex/bin/cli.js seed:run --specific=add_2028_reservations.cjs"
