# fly.toml file generated for spkulehas-api-staging on 2022-09-03T11:49:10-06:00

app = "spkulehas-api-staging"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/builder:22"

[env]
  PORT = "8080"
  BASE_URL="https://fly.io/apps/spkulehas-api-staging/api/v1/"
  FRONT_END_BASE_URL="https://spkulehas-staging.netlify.app/"
  FRONT_END_ORIGIN_URL="spkulehas-staging.netlify.app"
  MINIMUM_RESERVATION_DATE="2022-05-23"
  MAXIMUM_RESERVATION_DATE="2026-05-15"
  TZ="America/Denver"
  NODE_ENV="staging"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[deploy]
  release_command = "yarn migrate"
