#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Formatting for pre-commit'

(yarn format:write && yarn lint:fix) || 
(
    echo '❌ Linting errors found ❌'
    false;
)

echo '✅✅✅✅  Put a ring on it! ✅✅✅✅'
