name: Deploy Production
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: production
        required: true
jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config ./flyEnv/fly.production.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
