name: Deploy Staging
on:
  push:
    branches:
      - develop
      - feature/*
      - bugfix/*
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: staging
        required: true
jobs:
  deploy:
    name: Deploy staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: corepack enable && yarn compile && flyctl deploy ./build --config ./flyEnv/fly.staging.toml --local-only -a spkulehas-api-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
