name: Fly Deploy Staging
on:
push:
branches:
  - develop
env:
FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
deploy:
name: Deploy app
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - uses: superfly/flyctl-actions/setup-flyctl@master
  - run: flyctl deploy --config ./flyEnv/fly.staging.toml --remote-only

  name: Fly Deploy Production
on:
push:
branches:
  - Main
env:
FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
deploy:
name: Deploy app
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - uses: superfly/flyctl-actions/setup-flyctl@master
  - run: flyctl deploy --config ./flyEnv/fly.production.toml --remote-only